# Base configs
#baseurl: "https://photography.rampatra.com"
 baseurl: "https://kinghildad.github.io/photography" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Hildad"
subtitle: "See the world through my eyes!"
author: "Hildad Muchiri"
header:
 title: "Photography"
 subtitle: "by Hildad Muchiri"
footer:
 name: "Hey there, my name is Hildad"
 bio: "I am a software developer and a tech aficionado. Love making teeny tiny apps solving tiny problems in life and capturing moments through photography."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
web_design: "AJ"

social_urls:
twitter: "https://www.twitter.com/hildiddy"
  instagram: "https://www.instagram.com/_hildad"
  Tiktok: "https://tiktok.com/@_hildad"
  linkedin: "https://in.linkedin.com/in/hildad"
  github: "https://www.github.com/KingHildad"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
